Feature/center recipe modal and fix ingredient amounts
lauraguerra1/whats-cookin pull request #24
Opened 2023-05-21 23:58 UTC by mbenfowler

## Description
This pr:
- Moves the recipe modal to the center of the page and gives it a `max-width`
  - user can no longer scroll the main recipe list while viewing a recipe in the modal
- TDD for a function to remove extra decimals past 2 on ingredient amounts

Testing Notes
- Someone with a big screen, please test that the recipe modal is actually in the center for I cannot >_<
- Click on the "Pastry Cream" recipe at the bottom of the page
  - Ensure sucrose only has 2 decimal places
  - No other ingredients that have 2 or less decimal places should be affected

2023-05-21 23:58 UTC, mbenfowler commented
![](https://github.trello.services/images/mini-trello-icon.png) [[refactoring] center recipe card](https://trello.com/c/ZlFywsHZ/23-refactoring-center-recipe-card)

2023-05-22 04:16 UTC, taranveersingh93 requested changes

2023-05-22 04:16 UTC, taranveersingh93 commented on src/styles.css
> +  max-width: 1200px;
Can we achieve the same visuals if we change width from 98% to 60%?

2023-05-22 04:16 UTC, taranveersingh93 commented on src/styles.css
> +  top: 50%;
Also, if we're going for reduced width: how do you feel about reduced height as well? in 75% or 80% range? If it looks good to you.

2023-05-22 13:09 UTC, lauraguerra1 commented on src/styles.css
> +  max-width: 1200px;
@taranveersingh93 I feel like 60% is very small. Perhaps width at 85% would keep it dependent on the screen size without having to use pixels, and that would make it smaller, if we want it smaller. I tested out width at 60% and I think that looks too small.

2023-05-22 13:11 UTC, lauraguerra1 approved these changes

2023-05-22 13:11 UTC, lauraguerra1 commented on src/domUpdates.js
> +  body.classList.add('no-scroll')
Nice!

2023-05-22 13:11 UTC, lauraguerra1 commented on src/recipes.js
> +}
love this

2023-05-22 16:46 UTC, taranveersingh93 approved these changes
Thank you!

2023-05-22 16:49 UTC, merged