Feature/update readme
lauraguerra1/whats-cookin pull request #45
Opened 2023-06-05 21:57 UTC by lauraguerra1

Description
Update README

2023-06-05 22:13 UTC, taranveersingh93 requested changes

2023-06-05 22:13 UTC, taranveersingh93 commented on README.md
>  - Users are able to save recipes from the main landing page as well as from inside the recipe display.
save and delete?

2023-06-05 22:16 UTC, lauraguerra1 commented on README.md
>  - Users are able to save recipes from the main landing page as well as from inside the recipe display.
ohh good point, done now

2023-06-05 22:29 UTC, mbenfowler approved these changes
looks great!

2023-06-05 22:33 UTC, taranveersingh93 approved these changes

2023-06-05 22:33 UTC, merged

2023-06-06 13:58 UTC, mbenfowler commented
![](https://github.trello.services/images/mini-trello-icon.png) [update README](https://trello.com/c/dBVWNVpg/60-update-readme)